WatchYouWserver/config/routes.rb
Rails.application.routes.draw do

  resource 'users'
  
  resource 'schedules'
  
  get 'schedules/index'
  
  get 'schedules/delete'
  
  get 'schedules/json'
  
  get 'users/index'

  get 'users/new'

  get 'users/update'

  get 'users/json'
  
  get 'users/delete'
  
  get '/users' , to: 'users#index'
  
  get '/users/:id', to: 'users#show' 
  

   root 'users#index'

end

WatchYouWserver/app/models/schedule.rb
class Schedule < ActiveRecord::Base
	belongs_to :user
end

WatchYouWserver/app/models/user.rb
class User < ActiveRecord::Base
	has_many :schedules
end

WatchYouWserver/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

WatchYouWserver/app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  def new
	@userID = params[:userID]
	@schedule = Schedule.new
  end
  def index
	@userID = params[:userID]
	@schedule = Schedule.where(:userID => params[:userID])
  end
  
  def create
	@schedule = Schedule.new(post_params)
	@schedule.userID = params[:userID]
	if @schedule.save
		redirect_to schedules_index_path(:userID => @schedule.userID), notice => "saved"
	else
		render "new"
	end
  end
  def update
  end

  def delete
	if Schedule.destroy(params[:id])
			redirect_to schedules_path, :notice => "saved"
		else
			render "Show"
		end
  end
  
  def show
	@schedule = Schedule.find(params[:id])
  end
  
  def json
	@schedule = Schedule.where(:userID => params[:userID])
    render json: @schedule
  end
  
  private
    def post_params
        params.require(:schedule).permit(:date, :title, :category, :note, :star)
    end
end

WatchYouWserver/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
	@user = User.all
  end
  
  def new
	@user = User.new
  end
	
  def create
	@user = User.new(post_params)
	if @user.save
		redirect_to users_index_path, notice => "saved"
	else
		render "new"
	end
  end
	
  def update
		@user = User.find(params[:id])
		
		if @user.update_attributes(post_params)
			redirect_to user_path, :notice => "saved"
		else
			render "Edit"
		end
  end

  def delete
		@schedule = Schedule.where(:userID => params[:id])
		if @schedule.destroy_all && User.destroy(params[:id])
			redirect_to users_index_path, :notice => "saved"
		else
			render "show"
		end
  end
  
  def show
  	@user = User.find(params[:id])
  end
  
  def json
	@user = User.all
    render json: @user
  end
  private
    def post_params
        params.require(:user).permit(:name, :email, :password)
    end

end

WatchYouWserver/app/helpers/application_helper.rb
module ApplicationHelper
end

WatchYouWserver/app/helpers/schedules_helper.rb
module SchedulesHelper
end

WatchYouWserver/app/helpers/users_helper.rb
module UsersHelper
end

WatchYouWserver/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WatchYouWserver</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

WatchYouWserver/app/views/schedules/delete.html.erb
<h1>Schedules#delete</h1>
<p>Find me in app/views/schedules/delete.html.erb</p>

WatchYouWserver/app/views/schedules/index.html.erb
<h1>Schedules</h1>
<% @schedule.each do |s| %>
	<h3><%= link_to s.title, controller: "schedules", action: "show", id: s.id %></h3>
	<hr>
<% end %>
<h3><%= link_to "New", new_schedules_path(:userID => @userID) %></h3>
<%= link_to "Go Back", controller: "users", action: "show", id: @userID %>
<h3><%= link_to "JSON", controller: "schedules", action: "json", userID: @userID %></h3>

WatchYouWserver/app/views/schedules/new.html.erb
<h1>New Schedule</h1>
<%= form_for @schedule, url: {action: "create",controller: "schedules", userID: @userID} do |f| %>
	<p>
		<%=f.label :title %><br />
		<%=f.text_field :title %><br />
	</p>
	<p>
		<%=f.label :category %><br />
		<%=f.text_field :category %><br />
	</p>
	<p>
		<%=f.label :date %><br />
		<%=f.text_field :date %><br />
	</p>
	<p>
		<%=f.label :star %><br />
		<%=f.text_field :star %><br />
	</p>
		<p>
		<%=f.label :note %><br />
		<%=f.text_field :note %><br />
	</p>
	
	<p>
		<%= f.submit "Add Schedule" %>
	</p>
<% end %>
<%= link_to "Go Back", schedules_index_path(:userID => @userID) %>

WatchYouWserver/app/views/schedules/show.html.erb
<h1><%= @schedule.title %></h1>
<p>date: <%= @schedule.date %></p>
<p>category: <%= @schedule.category %></p>
<p>star: <%= @schedule.star %></p>
<p>category: <%= @schedule.note %></p>



<h3><%= link_to "Delete", controller: "schedules", action: "delete", id: @schedule.id %></h3>
<%= link_to "Go Back", controller: "schedules", action: "index" , userID: @schedule.userID%>

WatchYouWserver/app/views/schedules/update.html.erb
<h1>Schedules#update</h1>
<p>Find me in app/views/schedules/update.html.erb</p>

WatchYouWserver/app/views/users/delete.html.erb
<h1>Users#delete</h1>
<p>Find me in app/views/users/delete.html.erb</p>

WatchYouWserver/app/views/users/index.html.erb
<h1>Users Data</h1>
<% @user.each do |user| %>
	<h3><%= link_to user.name, controller: "users", action: "show", id: user.id %></h3>
	<hr>
<% end %>
<h3><%= link_to "New", users_new_path %></h3>
<h3><%= link_to "JSON", controller: "users", action: "json" %></h3>
<hr>

WatchYouWserver/app/views/users/json.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Index_of_Posts</title>
	<% @user.each do |user| %>
		<% if user.name %>
			<h3><%= user.name %></h3>
			<p><%= user.email %></p>
			<hr>
		<% end %>	
	<% end %>
</head>
<body>

<%= yield %>

</body>
</html>

WatchYouWserver/app/views/users/new.html.erb
<h1>New User</h1>
<%= form_for @user, url: {action: "create",controller: "users"} do |f| %>
	<p>
		<%=f.label :name %><br />
		<%=f.text_field :name %><br />
	</p>
	<p>
		<%=f.label :email %><br />
		<%=f.text_field :email %><br />
	</p>
	<p>
		<%=f.label :password %><br />
		<%=f.text_field :password %><br />
	</p>
	<p>
		<%= f.submit "Add User" %>
	</p>
<% end %>
<%= link_to "Go Back", users_index_path %>

WatchYouWserver/app/views/users/show.html.erb

<h1><%= @user.name %></h1>
<p>email: <%= @user.email %></p>
<p>password: <%= @user.password %></p>



<h3><%= link_to "Schedule", schedules_index_path(:userID => @user.id) %></h3>
<h3><%= link_to "Delete", controller: "users", action: "delete", id: @user.id %></h3>
<%= link_to "Go Back", controller: "users", action: "index" %>

WatchYouWserver/app/views/users/update.html.erb
<h1>Update User</h1>
<%= form_for @user do |f| %>
	<p>
		<%=f.label :name %><br />
		<%=f.text_field :name %><br />
	</p>
	<p>
		<%=f.label :email %><br />
		<%=f.text_field :email %><br />
	</p>
	<p>
		<%=f.label :password %><br />
		<%=f.text_field :password %><br />
	</p>
	<p>
		<%=f.label :scheduleID %><br />
		<%=f.text_field :scheduleID %><br />
	</p>
	<p>
		<%= f.submit "Edit User" %>
	</p>
<% end %>
<%= link_to "Go Back",user_path %>